# For more info on the VS Code REST Client, see: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
# @name getSignedUrl
# Step 1: Get a pre-signed URL from the backend.
# The response will be captured in a variable named 'getSignedUrl'.
POST http://localhost:3001/api/v1/moments/sign-batch
Content-Type: application/json

{
  "activityId": 1,
  "files": [
    {
      "fileName": "ducky.jpg",
      "fileType": "image/jpeg",
    }
  ]
}

###
# @name uploadToS3
# Step 2: Upload the dummy file to the pre-signed URL from the previous step.
# NOTE: You must run the "getSignedUrl" request above this one first!
# The variable {{getSignedUrl.response.body.0.signedUrl}} is automatically
# populated from the response of the first request.
PUT {{getSignedUrl.response.body.0.signedUrl}}
Content-Type: image/jpeg

< ./uploads/ducky.jpg

